# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_pedido_attendant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_count', models.IntegerField()),
                ('type', models.IntegerField()),
                ('hired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tel',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='attendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Usuario'),
        ),
        migrations.DeleteModel(
            name='Atendente',
        ),
        migrations.AddField(
            model_name='telefone',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Cliente'),
        ),
    ]
