# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_auto_20170407_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
